version: "2.2"
services:
  variantsexplorer-ui:
    build: .
    container_name: variantsexplorer-ui
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
    restart: unless-stopped

  mongoexpress:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    links:
      - mongo
    restart: unless-stopped

